### ISSUE TITLE
Help whit ATSP - Assimetric Traveling Salesman Problem

### ISSUE THREAD

**Issue by DiegoadMata** [yu961549745/MatlabCollections#1]
Hi

I'm Diego Mata and i study optimization in Brazil. 
I implemented your code and had great results.

The problem is that i did not understand the expansion to transform the asymmetric matrix into a symmetric matrix. 

do you have any paper that explain the technique used in this code?
I would like to reference them in my paper. 

I refer to the code available on github in the link below

https://github.com/yu961549745/MatlabCollections/tree/master/ATSP

**Comment by yu961549745** [comment]
Hi, nice to meet you. 
Here are the refered articles.
```
@article{Jonker1983Nov,
	author = {Jonker, Roy and Volgenant, Ton},
	title = {{Transforming asymmetric into symmetric traveling salesman problems}},
	journal = {Operations Research Letters},
	volume = {2},
	number = {4},
	pages = {161--163},
	year = {1983},
	month = {Nov},
	issn = {0167-6377},
	publisher = {North-Holland},
	doi = {10.1016/0167-6377(83)90048-2}
}
@article{Jonker1986Oct,
	author = {Jonker, Roy and Volgenant, Ton},
	title = {{Transforming asymmetric into symmetric traveling salesman problems: erratum}},
	journal = {Operations Research Letters},
	volume = {5},
	number = {4},
	pages = {215--216},
	year = {1986},
	month = {Oct},
	issn = {0167-6377},
	publisher = {North-Holland},
	doi = {10.1016/0167-6377(86)90081-7}
}
```

If you have Mathematica , you can try to use `wolframTSP` instead of `intlinprogTsp` to get better results. 

Good Luck!
